# Generated by Django 2.1.5 on 2021-01-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_slug',
        ),
    ]
