# Generated by Django 2.1.5 on 2021-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iShop', '0002_remove_item_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
