from gpiozero import LED
import time

X = int(input("First loop: "))
Y = int(input("Second loop: "))

led1 = LED(18)
led2 = LED(17)
led3 = LED(16)
led4 = LED(13)
led5 = LED(12)
led6 = LED(11)
led7 = LED(10)
led8 = LED(9)
led9 = LED(8)
led10 = LED(7)
led11 = LED(6)
led12 = LED(5)
led13 = LED(4)
led14 = LED(3)
led15 = LED(2)
led16 = LED(19)
led17 = LED(20)
led18 = LED(21)
led19 = LED(22)
led20 = LED(23)
led21 = LED(24)
led22 = LED(25)
led23 = LED(26)
led24 = LED(27)

while True:
    #one sequence
    led1.toggle()
    time.sleep(X)
    led2.toggle()
    time.sleep(X)
    led3.toggle()
    time.sleep(X)
    led4.toggle()
    time.sleep(X)
    led5.toggle()
    time.sleep(5)
    led6.toggle()
    time.sleep(X)
    led7.toggle()
    time.sleep(X)
    led8.toggle()
    time.sleep(X)
    led9.toggle()
    time.sleep(X)
    led10.toggle()
    time.sleep(X)
    led11.toggle()
    time.sleep(X)
    led12.toggle()
    time.sleep(5)
    led13.toggle()
    time.sleep(X)
    led14.toggle()
    time.sleep(X)
    led15.toggle()
    time.sleep(X)
    led16.toggle()
    time.sleep(X)
    led17.toggle()
    time.sleep(X)
    led18.toggle()
    time.sleep(X)
    led19.toggle()
    time.sleep(X)
    led20.toggle()
    time.sleep(X)
    led21.toggle()
    time.sleep(X)
    led22.toggle()
    time.sleep(X)
    led23.toggle()
    time.sleep(X)
    led24.toggle()
    time.sleep(X)
    led1.toggle()
    time.sleep(X)
    led2.toggle()
    time.sleep(X)
    led3.toggle()
    time.sleep(X)
    led4.toggle()
    time.sleep(X)
    led5.toggle()
    time.sleep(X)
    led6.toggle()
    time.sleep(X)
    led7.toggle()
    time.sleep(X)
    led8.toggle()
    time.sleep(X)
    led9.toggle()
    time.sleep(X)
    led10.toggle()
    time.sleep(X)
    led11.toggle()
    time.sleep(X)
    led12.toggle()
    time.sleep(X)
    led13.toggle()
    time.sleep(X)
    led14.toggle()
    time.sleep(X)
    led15.toggle()
    time.sleep(X)
    led16.toggle()
    time.sleep(X)
    led17.toggle()
    time.sleep(X)
    led18.toggle()
    time.sleep(X)
    led19.toggle()
    time.sleep(X)
    led20.toggle()
    time.sleep(X)
    led21.toggle()
    time.sleep(X)
    led22.toggle()
    time.sleep(X)
    led23.toggle()
    time.sleep(X)
    led24.toggle()
    time.sleep(X)
    #another sequence
    led1.toggle()
    time.sleep(Y)
    led1.toggle()
    led2.toggle()
    time.sleep(Y)
    led2.toggle()
    led3.toggle()
    time.sleep(Y)
    led3.toggle()
    led4.toggle()
    time.sleep(Y)
    led4.toggle()
    led5.toggle()
    time.sleep(Y)
    led5.toggle()
    led6.toggle()
    time.sleep(Y)
    led6.toggle()
    led7.toggle()
    time.sleep(Y)
    led7.toggle()
    led8.toggle()
    time.sleep(Y)
    led8.toggle()
    led9.toggle()
    time.sleep(Y)
    led9.toggle()
    led10.toggle()
    time.sleep(Y)
    led10.toggle()
    led11.toggle()
    time.sleep(Y)
    led11.toggle()
    led12.toggle()
    time.sleep(Y)
    led12.toggle()
    led13.toggle()
    time.sleep(Y)
    led13.toggle()
    led14.toggle()
    time.sleep(Y)
    led14.toggle()
    led15.toggle()
    time.sleep(Y)
    led15.toggle()
    led16.toggle()
    time.sleep(Y)
    led16.toggle()
    led17.toggle()
    time.sleep(Y)
    led17.toggle()
    led18.toggle()
    time.sleep(Y)
    led18.toggle()
    led19.toggle()
    time.sleep(Y)
    led19.toggle()
    led20.toggle()
    time.sleep(Y)
    led20.toggle()
    led21.toggle()
    time.sleep(Y)
    led21.toggle()
    led22.toggle()
    time.sleep(Y)
    led22.toggle()
    led23.toggle()
    time.sleep(Y)
    led23.toggle()
    led24.toggle()
    time.sleep(Y)
    led24.toggle()
